#!/usr/bin/env bash

# Check if any .js file changed
git diff --cached --name-only --diff-filter=ACM | grep -e '\.\(js\|css\|less\|styl\)$' >/dev/null 2>&1

if [[ $? == 0 ]]; then
    npm run precommit
fi

exit $?
