@startuml

!include ./shared.plantuml

title Common dependency relations

() Todos <<Source>>
() TodosHook <<Hook>>
() User <<Source>>
() UserHook <<Hook>>
() UserId <<Computed>>
() FilteredTodos <<Computed>>
() UserService <<Action>>
() UserLoadingStatus <<Status>>
() TodosFilter <<Source>>
() TodosView <<Component>>

Todos <- TodosHook

UserHook <- Todos

User <-- TodosHook
User -> UserHook

UserId <--User

UserService ..> TodosHook: Change source\nvia hooks
UserService ..> UserHook


FilteredTodos <-- Todos
FilteredTodos <- UserId
FilteredTodos <-- TodosFilter

UserLoadingStatus <.. Todos: Grabbed\nsrc
UserLoadingStatus <.. User: Grabbed\nsrc
UserLoadingStatus ..> FilteredTodos: Look into deep\ntree

TodosView <-- FilteredTodos
TodosView <-- UserLoadingStatus
TodosView <-- UserService: EventChanges

@enduml
